### ISSUE TITLE
Post a publishing calendar in a public place. Include info about when submitted news/links are due, editorial policy, and general expectations.

### ISSUE THREAD

**Issue by Yonet** [immersive-web/administrivia#114]

**Comment by TrevorFSmith** [comment]
The XMPP community uses GitHub Pull Requests in an interesting way to collaborate on their monthly newsletter.

Here's an example PR: https://github.com/xsf/xmpp.org/pull/714

I'd like to set up something similar since it keeps everything nice and open. Since the IWW is weekly (natch) I wonder how much interaction we'll get.

I also plan to create ways for people to submit links via a form and via email since not everyone has experience with GitHub or is comfy with git.

**Comment by TrevorFSmith** [comment]
Ok, I'm going to close this Issue since I've updated the main README about using pull requests and email to contribute links. I may open new issues (probably over on the IWW repo) as we figure out how it all works.
