### ISSUE TITLE
Launch the Working Group

### ISSUE THREAD

**Issue by AdaRoseCannon** [immersive-web/administrivia#15]
List
- [x] Email Dom, about pushing back launch until:
- [x] Update Github Readme
- [x] Launch Web Site
- [ ] Detail Transparency plans
- [x] Write Blog Post

Then

- [x] Publish W3C Blog Post
- [x] Social Media

**Comment by AdaRoseCannon** [comment]
@TrevorFSmith Are you able to update the community group landing page?

**Comment by TrevorFSmith** [comment]
Not that I'm aware of, but I'll ask Dom.

**Comment by TrevorFSmith** [comment]
Ok, I now have access to the WordPress installation (!!!) that powers the blog posts on https://www.w3.org/community/immersive-web/

Now I guess that we need to write a blog post!
Here are the things I think it should include:
- The Immersive Web has come a long way since the last blog post
- There's now a WG
- WebXR Device API is coming along nicely, thank you
- The CG is talking about topics beyond WebXR (with examples)

What else?
